# generated by datamodel-codegen:
#   filename:  cnap.match_v5.json
#   timestamp: 2025-02-08T23:40:00+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import Field

from models.GlobalPydanticConfig import BaseConfig


class Challenges(BaseConfig):
    field_12AssistStreakCount: int = Field(..., alias="12AssistStreakCount")
    InfernalScalePickup: int
    SWARM_DefeatAatrox: int
    SWARM_DefeatBriar: int
    SWARM_DefeatMiniBosses: int
    SWARM_EvolveWeapon: int
    SWARM_Have3Passives: int
    SWARM_KillEnemy: int
    SWARM_PickupGold: int
    SWARM_ReachLevel50: int
    SWARM_Survive15Min: int
    SWARM_WinWith5EvolvedWeapons: int
    abilityUses: int
    acesBefore15Minutes: int
    alliedJungleMonsterKills: int
    baronBuffGoldAdvantageOverThreshold: Optional[int] = None
    baronTakedowns: int
    blastConeOppositeOpponentCount: int
    bountyGold: int
    buffsStolen: int
    completeSupportQuestInTime: int
    controlWardTimeCoverageInRiverOrEnemyHalf: Optional[float] = None
    controlWardsPlaced: int
    damagePerMinute: float
    damageTakenOnTeamPercentage: float
    dancedWithRiftHerald: int
    deathsByEnemyChamps: int
    dodgeSkillShotsSmallWindow: int
    doubleAces: int
    dragonTakedowns: int
    earliestBaron: Optional[float] = None
    earlyLaningPhaseGoldExpAdvantage: int
    effectiveHealAndShielding: float
    elderDragonKillsWithOpposingSoul: int
    elderDragonMultikills: int
    enemyChampionImmobilizations: int
    enemyJungleMonsterKills: int
    epicMonsterKillsNearEnemyJungler: int
    epicMonsterKillsWithin30SecondsOfSpawn: int
    epicMonsterSteals: int
    epicMonsterStolenWithoutSmite: int
    firstTurretKilled: int
    firstTurretKilledTime: Optional[float] = None
    fistBumpParticipation: int
    flawlessAces: int
    fullTeamTakedown: int
    gameLength: float
    getTakedownsInAllLanesEarlyJungleAsLaner: Optional[int] = None
    goldPerMinute: float
    hadOpenNexus: int
    highestCrowdControlScore: Optional[int] = None
    immobilizeAndKillWithAlly: int
    initialBuffCount: int
    initialCrabCount: int
    jungleCsBefore10Minutes: float
    junglerTakedownsNearDamagedEpicMonster: int
    kTurretsDestroyedBeforePlatesFall: int
    kda: float
    killAfterHiddenWithAlly: int
    killParticipation: float
    killedChampTookFullTeamDamageSurvived: int
    killingSprees: int
    killsNearEnemyTurret: int
    killsOnOtherLanesEarlyJungleAsLaner: Optional[int] = None
    killsOnRecentlyHealedByAramPack: int
    killsUnderOwnTurret: int
    killsWithHelpFromEpicMonster: int
    knockEnemyIntoTeamAndKill: int
    landSkillShotsEarlyGame: int
    laneMinionsFirst10Minutes: int
    laningPhaseGoldExpAdvantage: Optional[int] = None
    legendaryCount: int
    legendaryItemUsed: List[int]
    lostAnInhibitor: int
    maxCsAdvantageOnLaneOpponent: float
    maxKillDeficit: int
    maxLevelLeadLaneOpponent: int
    mejaisFullStackInTime: int
    moreEnemyJungleThanOpponent: float
    multiKillOneSpell: int
    multiTurretRiftHeraldCount: int
    multikills: int
    multikillsAfterAggressiveFlash: int
    outerTurretExecutesBefore10Minutes: int
    outnumberedKills: int
    outnumberedNexusKill: int
    perfectDragonSoulsTaken: int
    perfectGame: int
    pickKillWithAlly: int
    playedChampSelectPosition: Optional[int] = None
    poroExplosions: int
    quickCleanse: int
    quickFirstTurret: int
    quickSoloKills: int
    riftHeraldTakedowns: int
    saveAllyFromDeath: int
    scuttleCrabKills: int
    skillshotsDodged: int
    skillshotsHit: int
    snowballsHit: int
    soloBaronKills: int
    soloKills: int
    soloTurretsLategame: Optional[int] = None
    stealthWardsPlaced: int
    survivedSingleDigitHpCount: int
    survivedThreeImmobilizesInFight: int
    takedownOnFirstTurret: int
    takedowns: int
    takedownsAfterGainingLevelAdvantage: int
    takedownsBeforeJungleMinionSpawn: int
    takedownsFirstXMinutes: int
    takedownsInAlcove: int
    takedownsInEnemyFountain: int
    teamBaronKills: int
    teamDamagePercentage: float
    teamElderDragonKills: int
    teamRiftHeraldKills: int
    tookLargeDamageSurvived: int
    turretPlatesTaken: int
    turretTakedowns: int
    turretsTakenWithRiftHerald: int
    twentyMinionsIn3SecondsCount: int
    twoWardsOneSweeperCount: int
    unseenRecalls: int
    visionScoreAdvantageLaneOpponent: float
    visionScorePerMinute: float
    voidMonsterKill: int
    wardTakedowns: int
    wardTakedownsBefore20M: int
    wardsGuarded: int
    earliestDragonTakedown: Optional[float] = None
    junglerKillsEarlyJungle: Optional[int] = None
    killsOnLanersEarlyJungleAsJungler: Optional[int] = None
    fastestLegendary: Optional[float] = None
    highestChampionDamage: Optional[int] = None
    highestWardKills: Optional[int] = None
    shortestTimeToAceFromFirstTakedown: Optional[float] = None
    fasterSupportQuestCompletion: Optional[int] = None
    HealFromMapSources: Optional[float] = None
    hadAfkTeammate: Optional[int] = None
    teleportTakedowns: Optional[int] = None


class Missions(BaseConfig):
    playerScore0: int
    playerScore1: int
    playerScore2: int
    playerScore3: int
    playerScore4: int
    playerScore5: int
    playerScore6: int
    playerScore7: int
    playerScore8: int
    playerScore9: int
    playerScore10: int
    playerScore11: int


class StatPerks(BaseConfig):
    defense: int
    flex: int
    offense: int


class Selection(BaseConfig):
    perk: int
    var1: int
    var2: int
    var3: int


class Style(BaseConfig):
    description: str
    selections: List[Selection]
    style: int


class Perks(BaseConfig):
    statPerks: StatPerks
    styles: List[Style]


class Participant(BaseConfig):
    allInPings: int
    assistMePings: int
    assists: int
    baronKills: int
    basicPings: int
    bountyLevel: int
    challenges: Optional[Challenges] = None
    champExperience: int
    champLevel: int
    championId: int
    championName: str
    championTransform: int
    commandPings: int
    consumablesPurchased: int
    damageDealtToBuildings: int
    damageDealtToObjectives: int
    damageDealtToTurrets: int
    damageSelfMitigated: int
    dangerPings: int
    deaths: int
    detectorWardsPlaced: int
    doubleKills: int
    dragonKills: int
    eligibleForProgression: bool
    enemyMissingPings: int
    enemyVisionPings: int
    firstBloodAssist: bool
    firstBloodKill: bool
    firstTowerAssist: bool
    firstTowerKill: bool
    gameEndedInEarlySurrender: bool
    gameEndedInSurrender: bool
    getBackPings: int
    goldEarned: int
    goldSpent: int
    holdPings: int
    individualPosition: str
    inhibitorKills: int
    inhibitorTakedowns: int
    inhibitorsLost: int
    item0: int
    item1: int
    item2: int
    item3: int
    item4: int
    item5: int
    item6: int
    itemsPurchased: int
    killingSprees: int
    kills: int
    lane: str
    largestCriticalStrike: int
    largestKillingSpree: int
    largestMultiKill: int
    longestTimeSpentLiving: int
    magicDamageDealt: int
    magicDamageDealtToChampions: int
    magicDamageTaken: int
    missions: Missions
    needVisionPings: int
    neutralMinionsKilled: int
    nexusKills: int
    nexusLost: int
    nexusTakedowns: int
    objectivesStolen: int
    objectivesStolenAssists: int
    onMyWayPings: int
    participantId: int
    pentaKills: int
    perks: Optional[Perks] = None
    physicalDamageDealt: int
    physicalDamageDealtToChampions: int
    physicalDamageTaken: int
    placement: int
    playerAugment1: int
    playerAugment2: int
    playerAugment3: int
    playerAugment4: int
    playerAugment5: int
    playerAugment6: int
    playerSubteamId: int
    profileIcon: int
    pushPings: int
    puuid: str
    quadraKills: int
    riotIdGameName: str
    riotIdTagline: str
    role: str
    sightWardsBoughtInGame: int
    spell1Casts: int
    spell2Casts: int
    spell3Casts: int
    spell4Casts: int
    subteamPlacement: int
    summoner1Casts: int
    summoner1Id: int
    summoner2Casts: int
    summoner2Id: int
    summonerId: str
    summonerLevel: int
    summonerName: str
    teamEarlySurrendered: bool
    teamId: int
    teamPosition: str
    timeCCingOthers: int
    timePlayed: int
    totalAllyJungleMinionsKilled: int
    totalDamageDealt: int
    totalDamageDealtToChampions: int
    totalDamageShieldedOnTeammates: int
    totalDamageTaken: int
    totalEnemyJungleMinionsKilled: int
    totalHeal: int
    totalHealsOnTeammates: int
    totalMinionsKilled: int
    totalTimeCCDealt: int
    totalTimeSpentDead: int
    totalUnitsHealed: int
    tripleKills: int
    trueDamageDealt: int
    trueDamageDealtToChampions: int
    trueDamageTaken: int
    turretKills: int
    turretTakedowns: int
    turretsLost: int
    unrealKills: int
    visionClearedPings: int
    visionScore: int
    visionWardsBoughtInGame: int
    wardsKilled: int
    wardsPlaced: int
    win: bool


class Ban(BaseConfig):
    championId: int
    pickTurn: int


class Baron(BaseConfig):
    first: bool
    kills: int


class Champion(BaseConfig):
    first: bool
    kills: int


class Dragon(BaseConfig):
    first: bool
    kills: int


class Horde(BaseConfig):
    first: bool
    kills: int


class Inhibitor(BaseConfig):
    first: bool
    kills: int


class RiftHerald(BaseConfig):
    first: bool
    kills: int


class Tower(BaseConfig):
    first: bool
    kills: int


class Objectives(BaseConfig):
    baron: Baron
    champion: Champion
    dragon: Dragon
    horde: Horde
    inhibitor: Inhibitor
    riftHerald: RiftHerald
    tower: Tower


class Team(BaseConfig):
    bans: List[Ban]
    objectives: Optional[Objectives] = None
    teamId: int
    win: bool


class Info(BaseConfig):
    endOfGameResult: str
    gameCreation: int
    gameDuration: int
    gameEndTimestamp: int
    gameId: int
    gameMode: str
    gameName: str
    gameStartTimestamp: int
    gameType: str
    gameVersion: str
    mapId: int
    participants: List[Participant]
    platformId: str
    queueId: int
    teams: List[Team]
    tournamentCode: str


class InfoSingle(BaseConfig):
    endOfGameResult: str
    gameCreation: int
    gameDuration: int
    gameEndTimestamp: int
    gameId: int
    gameMode: str
    gameName: str
    gameStartTimestamp: int
    gameType: str
    gameVersion: str
    mapId: int
    participants: Participant
    platformId: str
    queueId: int
    teams: List[Team]
    tournamentCode: str


class Metadata(BaseConfig):
    dataVersion: str
    matchId: str
    participants: List[str]


class MatchV5DTO(BaseConfig):
    metadata: Metadata
    info: Info


class MatchV5SingleDTO(BaseConfig):
    metadata: Metadata
    info: InfoSingle
